const expectedData = [
    {
        avatar: null,
        created_at: "2024-04-15T20:45:19.000000Z",
        dislikesCount: 1,
        firstName: "Piotr",
        id: 1,
        languages: {
            id: 1,
            name: "English",
            created_at: null,
            updated_at: null,
            pivot: {
                video_id: 1,
                language_id: 1,
                title: "filmik",
                description: "fajny opis filmu",
            },
        },
        likesCount: 0,
        reference_code: "1a7ULotn5s",
        status: "OK",
        tags: [
            {
                id: 1,
                name: "gothic",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 1,
                },
            },
            {
                id: 2,
                name: "rpg",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 2,
                },
            },
            {
                id: 3,
                name: "gothic1",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 3,
                },
            },
        ],
        thumbnail: "/storage/videos/1a7ULotn5spalic001.jpg",
        updated_at: "2024-04-15T20:45:19.000000Z",
        userName: "Piotr3233",
        video: "/storage/videos/1a7ULotn5spalic.mp4",
        views: 0,
        visibility: "Public",
    },
    {
        avatar: null,
        created_at: "2024-04-15T20:45:19.000000Z",
        dislikesCount: 1,
        firstName: "Piotr",
        id: 1,
        languages: {
            id: 1,
            name: "English",
            created_at: null,
            updated_at: null,
            pivot: {
                video_id: 1,
                language_id: 1,
                title: "filmik",
                description: "fajny opis filmu",
            },
        },
        likesCount: 0,
        reference_code: "1a7ULotn5s",
        status: "OK",
        tags: [
            {
                id: 1,
                name: "gothic",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 1,
                },
            },
            {
                id: 2,
                name: "rpg",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 2,
                },
            },
            {
                id: 3,
                name: "gothic1",
                created_at: "2024-04-17T10:18:19.000000Z",
                updated_at: "2024-04-17T10:18:19.000000Z",
                pivot: {
                    taggable_type: "App\\Models\\Video",
                    taggable_id: 1,
                    tag_id: 3,
                },
            },
        ],
        thumbnail: "/storage/videos/1a7ULotn5spalic001.jpg",
        updated_at: "2024-04-15T20:45:19.000000Z",
        userName: "Piotr3233",
        video: "/storage/videos/1a7ULotn5spalic.mp4",
        views: 0,
        visibility: "Public",
    },
];

export { expectedData };
